defaults:
  - env: "???"
  - _self_
  - optional envXalgo@_global_: mvmwm_${env}

wandb:
  notes: null
  tags: null

slurm_job_id: ${oc.env:SLURM_ARRAY_JOB_ID,${oc.env:SLURM_JOB_ID, none}}
slurm_array_task_id: ${oc.env:SLURM_ARRAY_TASK_ID,none}
