defaults:
  - sofaenv
  - _self_

name: GraspLiftAndTouch
_target_: pc_rl.envs.sofaenv.grasp_lift_and_touch.build

# pointcloud wrapper args
color: True
max_expected_num_points: 1500
depth_cutoff: 305
voxel_grid_size: 5.0
random_downsample: 1500
center: [0.0, -25.0, 250.0]
scale: 75

# env args
camera_reset_noise: [20.0, 20.0, 20.0, 20.0, 20.0, 20.0]
time_step: 0.05
settle_steps: 10
frame_skip: 2

goal_tolerance: 10.0
start_in_phase: grasp
end_in_phase: done
collision_punish_mode: constant
phase_any_rewards:
  collision_cauter_gripper: -0.1
  collision_cauter_gallbladder: -0.1
  collision_cauter_liver: -0.1
  collision_gripper_liver: -0.01
  distance_cauter_target: -1.0
  delta_distance_cauter_target: -1.0
  target_visible: 0.1
  gallbladder_is_grasped: 0.0
  new_grasp_on_gallbladder: 10.0
  lost_grasp_on_gallbladder: -10.0
  active_grasping_springs: 0.0
  delta_active_grasping_springs: 0.0
  gripper_pulls_gallbladder_out: 0.005
  overlap_gallbladder_liver: -0.1
  delta_overlap_gallbladder_liver: -0.01
  dynamic_force_on_gallbladder: -0.003
  successful_task: 50.0
  failed_task: 0.0
  cauter_action_violated_state_limits: 0.0
  cauter_action_violated_cartesian_workspace: 0.0
  gripper_action_violated_state_limits: 0.0
  gripper_action_violated_cartesian_workspace: 0.0
  phase_change: 0.0

phase_grasp_rewards:
  distance_gripper_graspable_region: -2.0
  delta_distance_gripper_graspable_region: -20.0

phase_touch_rewards:
  cauter_activation_in_target: 0.0
  cauter_delta_activation_in_target: 0.0
  cauter_touches_target: 0.0
  delta_distance_cauter_target: -10.0
