_target_: common.build_maniskill
env_kwargs:
  reward_mode: normalized_dense
  camera_cfgs:
    # converting an image at default resolution to a pointcloud is extremely expensive and wasteful
    width: ${...image_shape[1]}
    height: ${...image_shape[0]}
  renderer_kwargs:
    offscreen_only: True
    # if EGL_DEVICE_ID is set (e.g. by clusterduck for rendering resource),
    # then ask all environments to use it for rendering
    # otherwise, use cuda:0
    device: cuda:${oc.env:EGL_DEVICE_ID,0}
continuous_task: True  # never terminate trajectory, only time out
max_episode_steps: 200
